//Autogenerated code
namespace Models.Enums
{
    public enum NotificationTypeEnum
    {
		///<summary>System</summary>
		System = 1,

		///<summary>Mail</summary>
		Mail = 2,

		///<summary>SMS</summary>
		SMS = 3
    }
}